# Generated by Django 4.1.7 on 2023-06-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='length',
            field=models.FloatField(default=50.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='weight',
            field=models.FloatField(default=60.0),
            preserve_default=False,
        ),
    ]
