# Generated by Django 4.1.7 on 2023-05-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='types',
            field=models.CharField(choices=[('Admin', 'Admin'), ('patient', 'patient')], default='', max_length=10),
        ),
    ]
