# Generated by Django 4.1.7 on 2023-05-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='types',
        ),
    ]
