# Generated by Django 4.1.7 on 2023-06-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='account',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
