# Generated by Django 3.2.19 on 2023-08-17 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesmanager', '0005_rename_name_testmodel_test'),
        ('account', '0005_alter_account_gender_alter_account_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesmanager.media'),
        ),
    ]
