# Generated by Django 4.2.1 on 2023-08-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='file',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
