# Generated by Django 4.2.1 on 2023-08-05 15:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filesmanager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filesmanager', '0002_remove_testmodel_file_delete_media_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to=filesmanager.models.upload_profile_image_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpeg', '.jpg', '.png'])])),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='filesmanager.media')),
            ],
        ),
    ]
