# Generated by Django 4.2.1 on 2023-08-05 15:20

import django.core.validators
from django.db import migrations, models
import filesmanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('filesmanager', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=filesmanager.models.upload_profile_image_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
    ]
