# Generated by Django 4.2.1 on 2023-08-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesmanager', '0004_alter_media_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='name',
            new_name='test',
        ),
    ]
