# Generated by Django 3.2.19 on 2023-08-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesmanager', '0005_rename_name_testmodel_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
