# Generated by Django 4.1.7 on 2023-06-22 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 23, 0, 29, 21, 368257)),
        ),
    ]
