# Generated by Django 4.2.1 on 2023-07-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_reservations_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
