# Generated by Django 4.2.1 on 2023-05-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reservations_delete_reserrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user_id',
        ),
    ]
