# Generated by Django 4.2.1 on 2023-05-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_doctor_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
