# Generated by Django 4.2.1 on 2023-08-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_reservations_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='price',
        ),
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
