# Generated by Django 4.2.1 on 2023-05-04 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_doctor_doc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 4, 11, 12, 31, 111097), null=True),
        ),
    ]
