# Generated by Django 4.2.3 on 2023-08-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_doctor_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon_path',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='icon_path',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='price',
            field=models.IntegerField(),
        ),
    ]
