# Generated by Django 4.1.7 on 2023-05-23 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_reservations_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 23, 19, 52, 42, 818639), null=True),
        ),
    ]
