# Generated by Django 4.1.7 on 2023-06-08 15:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_reservations_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 8, 18, 15, 3, 368575), null=True),
        ),
    ]
