# Generated by Django 4.2.3 on 2023-08-21 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesmanager', '0005_rename_name_testmodel_test'),
        ('app', '0006_remove_service_icon_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_path',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesmanager.media'),
        ),
        migrations.AddField(
            model_name='specification',
            name='icon_path',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesmanager.media'),
        ),
    ]
