# Generated by Django 3.2.20 on 2023-08-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesmanager', '0006_delete_testmodel'),
        ('app', '0007_service_icon_path_specification_icon_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon_path',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesmanager.media'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='icon_path',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesmanager.media'),
        ),
    ]
