# Generated by Django 3.2.20 on 2023-08-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230822_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon_path',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='icon_path',
        ),
    ]
